# Generated by Django 5.0.4 on 2024-09-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_on_sale_product_space_type_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
