# Generated by Django 5.0.4 on 2024-09-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
